---
- name: Ensure Nginx is installed
  yum:
    name: nginx
    state: present

- name: Ensure Nginx is started
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy a simple index.html file
  copy:
    content: |
      <html>
      <head>
        <title>Welcome to my nginx server!</title>
      </head>
      <body>
        <h1>Success! The NGINX HTTP Server is installed and running.</h1>
      </body>
      </html>
    dest: /usr/share/nginx/html/index.html
