---
- name: Ensure Apache is installed
  yum:
    name: httpd
    state: present

- name: Ensure Apache is started
  service:
    name: httpd
    state: started
    enabled: yes

- name: Deploy a simple index.html file
  copy:
    content: |
      <html>
      <head>
        <title>Welcome to my web server!</title>
      </head>
      <body>
        <h1>Success! The Apache HTTP Server is installed and running.</h1>
      </body>
      </html>
    dest: /var/www/html/index.html

- name: vars
  debug:
    msg: "gropu_var_sample: {{gropu_var_sample}}, var_a: {{var_a}}, var_b: {{var_a}}"
